### ISSUE TITLE
Data Cleaning Issue

### ISSUE THREAD

**Issue by liuaoqi** [liuaoqi/tci_machine_learning#1]
https://github.com/liuaoqi/tci_machine_learning/blob/27e3784eaabc705f845752930416a4b597393a28/data_processor.py#L25-L39

- Digits are not processed efficiently
- Some data (currency) might not be recognized caused by improper data cleaning process

**Comment by laniloo94** [comment]
(✿◕‿◕✿)great

**Comment by liuaoqi** [comment]
Updates:
- Ignore currency
- Only read percentage data
